### ISSUE TITLE
Permission denied issue when connecting to the Docker daemon socket

### ISSUE THREAD

**Issue by slauriere** [STAMP-project/tecor#2]
Hi, 

I gave a try to Tecor as is, the first steps went fine but the script fires a permission denied issue when trying to connect to the Docker daemon socket. I'm attaching the full log below. I ran the 'deploy.sh' script also as root without more success. Do you have any idea about what causes the problem? Thanks a lot.

Execution log: [tecor.log](https://github.com/STAMP-project/tecor/files/1643691/tecor.log)

**Comment by vassik** [comment]
Hi. You need to change the value of DOCKERGID in deploy.sh. You can find out a group id, by locking up ‘docker’ in /etc/groups, given that ‘docker’ is a name of the group which owns the docker socket.

**Comment by slauriere** [comment]
Thank you @vassik I had overlooked the GID part in the README.
